### ISSUE TITLE
Draw 2 racks side by side

### ISSUE THREAD

**Issue by pjahn** [ashrafhasson/dokuwiki-plugin-advrack#1]
Is there a trick to draw 2 racks side by side?

**Comment by ashrafhasson** [comment]
I have some half-working code somewhere to support showing the front and the back of a rack side-by-side, or so was my intention.
I'll try to find some time to add this ability.

**Comment by ashrafhasson** [comment]
@pjahn apologies, I've not found time for this and clearly haven't prioritized maintaining this plugin. I'll close for now. I hope someone will suggest taking over if this is still useful.
